#!/usr/bin/env bash
source node_config && source node_bootstrap
sc_name=`basename "$0"`

# Set default version
if [[ "$UMEE_BINARY_VERSION" = "" ]]; then
  UMEE_BINARY_VERSION=v4.2.0
fi

# Get the binary
node_log "Fetching binary $UMEE_BINARY_VERSION"
wget --no-check-certificate https://github.com/umee-network/umee/releases/download/${UMEE_BINARY_VERSION}/umeed-${UMEE_BINARY_VERSION}-linux-amd64  || node_exit "Unable to download binary"

# Check if the binary exists
if [[ -e umeed-${UMEE_BINARY_VERSION}-linux-amd64 ]]; then
    mv umeed-${UMEE_BINARY_VERSION}-linux-amd64 umeed && chmod +x umeed && mv umeed /usr/bin
    node_log "Binary downloaded and setup"
else
    node_exit "Aborting, unable to find binary"
fi

node_log "Bootstrap node . ." && mv node_* /tmp
node_start

ssh-keygen -A && mkdir -p /run/sshd
exec /usr/sbin/sshd -D